apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ollama
  namespace: ollama-granite-demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: gp3-csi
